name: Test build
on:
  pull_request:
    paths-ignore:
      - '**/README.md'
      - 'website/'

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install cppcheck
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Run static analysis
      run: |
        make static-analysis
    - name: Test
      shell: bash
      run: |
        make test
